[package]
name = "ch7_database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
action_kv = { path = "./action_kv" }
byteorder = "1.4.3"
crc = "1.7"